In [2]:

from alpaca.data.historical.news import NewsClient
from alpaca.data.requests import NewsRequest
from datetime import datetime

api_key='PKSFPBOGXCM4LWVR3T2JHYHAIU'
secret_key='7JFMkCuQ98bVAJHDeyo4bw3RGSic7CmpmGdUk4cntPv'
# no keys required for news data
client = NewsClient(api_key=api_key,secret_key=secret_key)

request_params = NewsRequest(
                        symbols="AAPL",
                        start=datetime.strptime('2016-01-01', '%Y-%m-%d'),
                        end=datetime.strptime('2023-12-01', '%Y-%m-%d'),
                        include_content=True,
                        exclude_contentless = True  
                        )

news = client.get_news(request_params)

# convert to dataframe
data=news.df
data

,headline,source,url,summary,created_at,updated_at,symbols,author,content,images
id,,,,,,,,,,
36032435,Amazon Grabs More Live Sports Rights With NASC...,benzinga,https://www.benzinga.com/general/entertainment...,Amazon&#39;s streaming platform Prime Video is...,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,"[AAPL, AMZN, CMCSA, FOX, FOXA, FWONA, FWONK, WBD]",Chris Katje,<p>Streaming companies continue to enter the r...,"[{'size': 'NewsImageSize.LARGE', 'url': 'https..."
36026956,British Antitrust Watchdog Wins Appeal In UK C...,benzinga,https://www.benzinga.com/government/23/11/3602...,Today&#39;s unanimous judgment from the U.K. C...,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,"[AAPL, GOOG, GOOGL]",Anusuya Lahiri,<p>Today&#39;s unanimous judgment from the U.K...,"[{'size': 'NewsImageSize.LARGE', 'url': 'https..."
36022768,Meta's Metaverse Ambitions Hit A Roadblock,benzinga,https://www.benzinga.com/news/23/11/36022768/m...,Meta Platforms Inc&#39;s (NASDAQ: META) Quest ...,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,"[AAPL, META, T, TMUS, VZ]",Anusuya Lahiri,<p><strong>Meta Platforms Inc&#39;s</strong>&n...,"[{'size': 'NewsImageSize.LARGE', 'url': 'https..."
36028948,10 Information Technology Stocks Whale Activit...,benzinga,https://www.benzinga.com/markets/options/23/11...,,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,"[AAPL, AMD, AVGO, CLSK, CRM, CRWD, NVDA, ON, P...",Benzinga Insights,<p>This whale alert can help traders discover ...,"[{'size': 'NewsImageSize.LARGE', 'url': 'https..."
36028415,Musk In A Rage Over Twitter Ad Boycotts: Why T...,benzinga,https://www.benzinga.com/news/23/11/36028415/m...,Social media platform Twitter was acquired for...,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,"[AAPL, AMZN, DIS, IBM, KO, MSFT, WBD]",Chris Katje,"<p>In a viral moment caught on camera, social ...","[{'size': 'NewsImageSize.LARGE', 'url': 'https..."
...,...,...,...,...,...,...,...,...,...,...
6057395,TOp 20 Analysts For 2015,,https://www.benzinga.com/node/6057395,,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,"[AAPL, ADI, AET, AGN, AIG, ALK, AMBA, AMD, AMZ...",Benzinga,<ul><em>TipRanks gathers analyst ratings and r...,[]
6101905,Download Microsoft With This ETF,,https://www.benzinga.com/node/6101905,,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,"[AAPL, IYW, MSFT]",Benzinga,"<p style=""margin-bottom: 0in"">\r\n\tLast year,...",[]
6091910,Fast Money Traders Are Bullish On McDonald's C...,,https://www.benzinga.com/node/6091910,,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,"[AAPL, MCD, NFLX]",Benzinga,"<a href=""http://video.cnbc.com/gallery/?video=...",[]
6096812,Global Equities' Trip Chowdhry Blasts Apple Ma...,,https://www.benzinga.com/node/6096812,,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,[AAPL],Benzinga,<p>\r\n\tTrip Chowdhry of Global Equities Rese...,[]
6088089,The Two Best Sector SPDR ETFs For January,,https://www.benzinga.com/node/6088089,,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,"[AAPL, FB, GOOG, JNJ, PFE, UNH, XLK, XLV]",Benzinga,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi...",[]

In [3]:
data=data.reset_index()[['id', 'created_at', 'updated_at', 'headline', 'content']]
data

,id,created_at,updated_at,headline,content
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...
2,36022768,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,Meta's Metaverse Ambitions Hit A Roadblock,<p><strong>Meta Platforms Inc&#39;s</strong>&n...
3,36028948,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,10 Information Technology Stocks Whale Activit...,<p>This whale alert can help traders discover ...
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ..."
...,...,...,...,...,...
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...
14331,6101905,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,Download Microsoft With This ETF,"<p style=""margin-bottom: 0in"">\r\n\tLast year,..."
14332,6091910,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,Fast Money Traders Are Bullish On McDonald's C...,"<a href=""http://video.cnbc.com/gallery/?video=..."
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi..."

In [4]:
data.to_pickle('new_data.pickle')

In [5]:
import pandas as pd
data=pd.read_pickle('new_data.pickle')
data

,id,created_at,updated_at,headline,content
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...
2,36022768,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,Meta's Metaverse Ambitions Hit A Roadblock,<p><strong>Meta Platforms Inc&#39;s</strong>&n...
3,36028948,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,10 Information Technology Stocks Whale Activit...,<p>This whale alert can help traders discover ...
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ..."
...,...,...,...,...,...
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...
14331,6101905,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,Download Microsoft With This ETF,"<p style=""margin-bottom: 0in"">\r\n\tLast year,..."
14332,6091910,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,Fast Money Traders Are Bullish On McDonald's C...,"<a href=""http://video.cnbc.com/gallery/?video=..."
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi..."