In [12]:
!pip3 install vaderSentiment

Requirement already satisfied: vaderSentiment in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (3.3.2)
Requirement already satisfied: requests in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (from requests->vaderSentiment) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/algo trading 2026/batch35/.venv/lib/python3.13/site-packages (from requests->vaderSentiment) (2026.1.4)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [13]:
# Import SentimentIntensityAnalyzer class
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
# Create an object of SentimentIntensityAnalyzer class
analyzer = SentimentIntensityAnalyzer()
str1='GOOGL is the BEST stock to invest in the entire world'
analyzer.polarity_scores(str1)

{'neg': 0.0, 'neu': 0.67, 'pos': 0.33, 'compound': 0.7125}

In [14]:
# For data manipulation
import pandas as pd

# For plotting data
import matplotlib.pyplot as plt

# Load the news data from a pickle file
news = pd.read_pickle("/Users/algo trading 2026/batch35/23_sentiment_analysis/new_data.pickle")
# news=pd.read_csv('/Users/algotrading2024/batch 29/news2.csv')
# Print the data
news

,id,created_at,updated_at,headline,content
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...
2,36022768,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,Meta's Metaverse Ambitions Hit A Roadblock,<p><strong>Meta Platforms Inc&#39;s</strong>&n...
3,36028948,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,10 Information Technology Stocks Whale Activit...,<p>This whale alert can help traders discover ...
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ..."
...,...,...,...,...,...
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...
14331,6101905,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,Download Microsoft With This ETF,"<p style=""margin-bottom: 0in"">\r\n\tLast year,..."
14332,6091910,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,Fast Money Traders Are Bullish On McDonald's C...,"<a href=""http://video.cnbc.com/gallery/?video=..."
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi..."

In [15]:
# Extract the date from the 'updated_at' column
news['date'] = [str(x)[:10] for x in news['updated_at']]
news

,id,created_at,updated_at,headline,content,date
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...,2023-11-30
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...,2023-11-30
2,36022768,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,Meta's Metaverse Ambitions Hit A Roadblock,<p><strong>Meta Platforms Inc&#39;s</strong>&n...,2023-11-30
3,36028948,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,10 Information Technology Stocks Whale Activit...,<p>This whale alert can help traders discover ...,2023-11-30
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ...",2023-11-30
...,...,...,...,...,...,...
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...,2016-01-04
14331,6101905,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,Download Microsoft With This ETF,"<p style=""margin-bottom: 0in"">\r\n\tLast year,...",2016-01-04
14332,6091910,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,Fast Money Traders Are Bullish On McDonald's C...,"<a href=""http://video.cnbc.com/gallery/?video=...",2016-01-04
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...,2016-01-03
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi...",2016-01-03

In [16]:
# Calculate the compound sentiment score for each headline
news["compound_score"] = news.headline.apply(lambda t: analyzer.polarity_scores(t)['compound'])
news

,id,created_at,updated_at,headline,content,date,compound_score
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...,2023-11-30,0.3612
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...,2023-11-30,0.5719
2,36022768,2023-11-30 18:20:27+00:00,2023-11-30 18:20:28+00:00,Meta's Metaverse Ambitions Hit A Roadblock,<p><strong>Meta Platforms Inc&#39;s</strong>&n...,2023-11-30,0.0000
3,36028948,2023-11-30 17:35:14+00:00,2023-11-30 17:35:15+00:00,10 Information Technology Stocks Whale Activit...,<p>This whale alert can help traders discover ...,2023-11-30,0.0000
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ...",2023-11-30,-0.8934
...,...,...,...,...,...,...,...
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...,2016-01-04,0.2023
14331,6101905,2016-01-04 13:48:54+00:00,2016-01-04 13:48:54+00:00,Download Microsoft With This ETF,"<p style=""margin-bottom: 0in"">\r\n\tLast year,...",2016-01-04,0.0000
14332,6091910,2016-01-04 11:15:03+00:00,2016-01-04 11:15:03+00:00,Fast Money Traders Are Bullish On McDonald's C...,"<a href=""http://video.cnbc.com/gallery/?video=...",2016-01-04,0.0000
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...,2016-01-03,0.4588
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi...",2016-01-03,0.6369

In [17]:
# Filter out news with non-zero sentiment scores
news_filtered = news.loc[news["compound_score"] != 0, :]
news_filtered

,id,created_at,updated_at,headline,content,date,compound_score
0,36032435,2023-11-30 20:24:41+00:00,2023-11-30 20:24:41+00:00,Amazon Grabs More Live Sports Rights With NASC...,<p>Streaming companies continue to enter the r...,2023-11-30,0.3612
1,36026956,2023-11-30 18:30:36+00:00,2023-11-30 18:30:36+00:00,British Antitrust Watchdog Wins Appeal In UK C...,<p>Today&#39;s unanimous judgment from the U.K...,2023-11-30,0.5719
4,36028415,2023-11-30 17:11:48+00:00,2023-11-30 17:22:40+00:00,Musk In A Rage Over Twitter Ad Boycotts: Why T...,"<p>In a viral moment caught on camera, social ...",2023-11-30,-0.8934
5,36026438,2023-11-30 15:54:14+00:00,2023-11-30 15:56:12+00:00,Apple's Resurgence - Gearing Up For A Monument...,<ul>\r\n\t<li>Apple is reportedly considering ...,2023-11-30,0.2244
7,36025372,2023-11-30 15:21:42+00:00,2023-11-30 15:23:16+00:00,Fed's Favorite Inflation Gauge Disappoints Bot...,"<p><em>To gain an edge, this is what you need ...",2023-11-30,0.1027
...,...,...,...,...,...,...,...
14328,6104596,2016-01-04 15:00:57+00:00,2016-01-04 15:00:57+00:00,FBR: Apple Growth Fears 'Overblown',<ul>\r\n\t<li>\r\n\t\t<em><strong>Apple Inc. <...,2016-01-04,-0.0516
14329,6101953,2016-01-04 14:38:32+00:00,2016-01-04 14:38:32+00:00,This Dividend ETF Looks Primed For A Solid 2016,"<p style=""margin-bottom: 0in"">\r\n\tLast year ...",2016-01-04,0.1531
14330,6057395,2015-12-17 15:44:51+00:00,2016-01-04 13:52:26+00:00,TOp 20 Analysts For 2015,<ul><em>TipRanks gathers analyst ratings and r...,2016-01-04,0.2023
14333,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...,2016-01-03,0.4588
14334,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi...",2016-01-03,0.6369

In [18]:
news_daily_count = news_filtered.groupby(
    "date")["date"].agg('count').to_frame('total_news_articles')
news_daily_count

            total_news_articles
date
2016-01-03                    2
2016-01-04                    5
2016-01-05                    4
2016-01-06                    7
2016-01-07                    9
...                         ...
2023-11-25                    3
2023-11-27                    4
2023-11-28                    7
2023-11-29                    9
2023-11-30                   11

[2079 rows x 1 columns]

In [19]:
# Set the date as the index for the news_filtered dataframe
news_filtered.set_index("date", inplace=True)

# Join the total news count with the news_filtered dataframe
news_filtered = news_filtered.join(news_daily_count, how='outer')

# Print the data
# print(news_filtered)

# Calculate the sentiment score by dividing the compound score by the total news articles for each date
news_filtered["sentiment_score"] = news_filtered["compound_score"] / news_filtered["total_news_articles"]
news_filtered

,id,created_at,updated_at,headline,content,compound_score,total_news_articles,sentiment_score
date,,,,,,,,
2016-01-03,6096812,2016-01-03 15:26:39+00:00,2016-01-03 15:30:26+00:00,Global Equities' Trip Chowdhry Blasts Apple Ma...,<p>\r\n\tTrip Chowdhry of Global Equities Rese...,0.4588,2,0.229400
2016-01-03,6088089,2016-01-03 01:29:48+00:00,2016-01-03 01:29:49+00:00,The Two Best Sector SPDR ETFs For January,"<p style=""margin-bottom: 0in"">\r\n\tA disappoi...",0.6369,2,0.318450
2016-01-04,6104722,2016-01-04 15:14:23+00:00,2016-01-04 15:15:52+00:00,Has The NFL's Audience Reached Its Peak?,<p>\r\n\tPacific Crest analysts took a deep lo...,0.1027,5,0.020540
2016-01-04,6104651,2016-01-04 15:03:06+00:00,2016-01-04 15:04:25+00:00,Apple Would Be Worth $1 Trillion If Market Val...,<p>\r\n\tIn a note that made waves this weeken...,0.7430,5,0.148600
2016-01-04,6104596,2016-01-04 15:00:57+00:00,2016-01-04 15:00:57+00:00,FBR: Apple Growth Fears 'Overblown',<ul>\r\n\t<li>\r\n\t\t<em><strong>Apple Inc. <...,-0.0516,5,-0.010320
...,...,...,...,...,...,...,...,...
2023-11-30,36013078,2023-11-29 21:57:18+00:00,2023-11-30 12:38:00+00:00,Fed's Favorite Inflation Gauge Arrives Thursda...,<p>The Bureau of Economic Analysis is set to r...,0.4588,11,0.041709
2023-11-30,36018001,2023-11-30 10:12:11+00:00,2023-11-30 10:12:11+00:00,Apple Resists Arm's Payment Hike Demand Despit...,<p><strong>Apple Inc.</strong> (NASDAQ:<a clas...,0.0997,11,0.009064
2023-11-30,36017656,2023-11-30 09:34:44+00:00,2023-11-30 09:34:45+00:00,GTA Trilogy Lands On Netflix Games: Here's How...,<p><strong>Netflix</strong> is set to expand i...,0.3400,11,0.030909
2023-11-30,36017011,2023-11-30 08:41:36+00:00,2023-11-30 08:41:36+00:00,"AllTrails, Photomator And Generative AI: Here ...",<p><strong>Apple Inc.</strong> (NASDAQ:<a clas...,0.7269,11,0.066082
2023-11-30,36016779,2023-11-30 07:59:57+00:00,2023-11-30 07:59:58+00:00,Free Speech Or Foul Speech? Yaccarino Wrestles...,<p><strong>X</strong> CEO <strong>Linda Yaccar...,0.5106,11,0.046418

In [20]:
# Sum the sentiment scores for each date
sum_of_sentiments = news_filtered.sentiment_score.groupby("date").sum()
sum_of_sentiments

date
2016-01-03    0.547850
2016-01-04    0.229900
2016-01-05   -0.373400
2016-01-06    0.036757
2016-01-07    0.099533
                ...
2023-11-25    0.371000
2023-11-27    0.164775
2023-11-28    0.396957
2023-11-29   -0.071000
2023-11-30    0.270745
Name: sentiment_score, Length: 2079, dtype: float64

In [21]:
# Create the dataframe `daily_sentiment_data`
daily_sentiment_data = pd.DataFrame()

# Calculate the mean total news articles for each date
daily_sentiment_data = news_filtered.groupby("date")[["total_news_articles"]].mean()

# Add the sum of sentiment scores to the daily_sentiment_data dataframe
daily_sentiment_data["sentiment_score"] = sum_of_sentiments
daily_sentiment_data

            total_news_articles  sentiment_score
date
2016-01-03                  2.0         0.547850
2016-01-04                  5.0         0.229900
2016-01-05                  4.0        -0.373400
2016-01-06                  7.0         0.036757
2016-01-07                  9.0         0.099533
...                         ...              ...
2023-11-25                  3.0         0.371000
2023-11-27                  4.0         0.164775
2023-11-28                  7.0         0.396957
2023-11-29                  9.0        -0.071000
2023-11-30                 11.0         0.270745

[2079 rows x 2 columns]

In [22]:
daily_sentiment_data.to_csv('daily_sentiment_scores_2016_jan_2023_sep.csv')