In [7]:
import pandas as pd
df=pd.read_csv('AMZN.csv')
df.rename(columns={'timestamp':'Datetime','open':'Open','high':'High','low':'Low','close':'Close','volume':'Volume'},inplace=True)
df=df[['Datetime','Open','High','Low','Close','Volume']]
#change timezone to america/new_york

df['Datetime']=pd.to_datetime(df['Datetime'])
df['Datetime']=df['Datetime'].dt.tz_convert('America/New_York')
df.set_index('Datetime',inplace=True)
# keep only regular trading hours (09:30–16:00 America/New_York)

df

                               Open    High     Low    Close  Volume
Datetime
2024-11-14 07:51:00-05:00  215.1700  215.17  215.15  215.160  7318.0
2024-11-14 07:53:00-05:00  215.2600  215.26  215.20  215.200   425.0
2024-11-14 07:54:00-05:00  215.2500  215.25  215.18  215.180   877.0
2024-11-14 07:57:00-05:00  215.1700  215.19  215.11  215.120  3162.0
2024-11-14 07:58:00-05:00  215.1100  215.11  215.09  215.090  1545.0
...                             ...     ...     ...      ...     ...
2026-03-27 19:55:00-04:00  198.6000  198.70  198.60  198.698  1100.0
2026-03-27 19:56:00-04:00  198.6206  198.65  198.62  198.620  1373.0
2026-03-27 19:57:00-04:00  198.6100  198.63  198.55  198.600  7145.0
2026-03-27 19:58:00-04:00  198.5500  198.59  198.54  198.540  2469.0
2026-03-27 19:59:00-04:00  198.5300  198.53  198.42  198.420  6813.0

[261163 rows x 5 columns]

In [8]:
df = df.between_time('09:30', '16:00')

In [9]:
df

                              Open      High       Low     Close     Volume
Datetime
2024-11-14 09:30:00-05:00  214.160  214.5300  213.9600  214.4200   927348.0
2024-11-14 09:31:00-05:00  214.400  215.3000  214.3600  215.0800   350326.0
2024-11-14 09:32:00-05:00  215.100  215.2390  214.8234  215.0999   257689.0
2024-11-14 09:33:00-05:00  215.100  215.4800  214.9900  215.3350   192097.0
2024-11-14 09:34:00-05:00  215.320  215.7300  215.3200  215.6300   265552.0
...                            ...       ...       ...       ...        ...
2026-03-27 15:56:00-04:00  199.425  199.4350  199.2350  199.3400   233724.0
2026-03-27 15:57:00-04:00  199.345  199.4500  199.2950  199.4000   283187.0
2026-03-27 15:58:00-04:00  199.410  199.5100  199.3807  199.4700   414538.0
2026-03-27 15:59:00-04:00  199.470  199.6600  199.2800  199.3200  1099976.0
2026-03-27 16:00:00-04:00  199.300  199.3647  199.1000  199.3200  6764850.0

[133030 rows x 5 columns]

In [10]:
import pandas as pd
df1=pd.read_csv('TSLA.csv')
df1.rename(columns={'date':'Datetime','open':'Open','high':'High','low':'Low','close':'Close','volume':'Volume'},inplace=True)
df1=df1[['Datetime','Open','High','Low','Close','Volume']]
#change timezone to america/new_york

df1['Datetime']=pd.to_datetime(df1['Datetime'])
# df1['Datetime']=df1['Datetime'].dt.tz_convert('America/New_York')
df1.set_index('Datetime',inplace=True)
df1

/var/folders/gf/2xw81y_n41x8mbjy1d6lp0540000gn/T/ipykernel_10792/1438217627.py:7: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df1['Datetime']=pd.to_datetime(df1['Datetime'])

                             Open    High     Low   Close  Volume
Datetime
2026-02-26 09:30:00-05:00  414.50  416.80  413.15  413.40    -1.0
2026-02-26 09:31:00-05:00  413.40  413.41  412.38  413.08    -1.0
2026-02-26 09:32:00-05:00  413.08  414.16  411.71  412.00    -1.0
2026-02-26 09:33:00-05:00  412.00  412.45  410.96  412.24    -1.0
2026-02-26 09:34:00-05:00  412.24  412.50  411.37  411.65    -1.0
...                           ...     ...     ...     ...     ...
2024-12-03 15:55:00-05:00  350.09  350.57  350.00  350.48    -1.0
2024-12-03 15:56:00-05:00  350.48  350.88  350.47  350.86    -1.0
2024-12-03 15:57:00-05:00  350.86  351.09  350.52  351.09    -1.0
2024-12-03 15:58:00-05:00  351.09  351.61  351.08  351.43    -1.0
2024-12-03 15:59:00-05:00  351.43  351.61  351.17  351.38    -1.0

[135210 rows x 5 columns]

In [15]:
df.sort_index()

                              Open      High       Low     Close     Volume
Datetime
2024-11-14 09:30:00-05:00  214.160  214.5300  213.9600  214.4200   927348.0
2024-11-14 09:31:00-05:00  214.400  215.3000  214.3600  215.0800   350326.0
2024-11-14 09:32:00-05:00  215.100  215.2390  214.8234  215.0999   257689.0
2024-11-14 09:33:00-05:00  215.100  215.4800  214.9900  215.3350   192097.0
2024-11-14 09:34:00-05:00  215.320  215.7300  215.3200  215.6300   265552.0
...                            ...       ...       ...       ...        ...
2026-03-27 15:56:00-04:00  199.425  199.4350  199.2350  199.3400   233724.0
2026-03-27 15:57:00-04:00  199.345  199.4500  199.2950  199.4000   283187.0
2026-03-27 15:58:00-04:00  199.410  199.5100  199.3807  199.4700   414538.0
2026-03-27 15:59:00-04:00  199.470  199.6600  199.2800  199.3200  1099976.0
2026-03-27 16:00:00-04:00  199.300  199.3647  199.1000  199.3200  6764850.0

[133030 rows x 5 columns]

In [13]:
df1.sort_index()

                             Open    High     Low   Close  Volume
Datetime
2024-11-04 09:30:00-05:00  244.54  245.31  244.27  244.63    -1.0
2024-11-04 09:31:00-05:00  244.63  244.97  242.83  242.95    -1.0
2024-11-04 09:32:00-05:00  242.95  243.69  242.02  242.10    -1.0
2024-11-04 09:33:00-05:00  242.10  242.22  241.46  241.60    -1.0
2024-11-04 09:34:00-05:00  241.60  242.15  241.49  241.68    -1.0
...                           ...     ...     ...     ...     ...
2026-03-27 15:55:00-04:00  361.21  362.46  361.21  362.13    -1.0
2026-03-27 15:56:00-04:00  362.13  362.14  361.76  361.94    -1.0
2026-03-27 15:57:00-04:00  361.94  362.03  361.60  361.86    -1.0
2026-03-27 15:58:00-04:00  361.86  362.14  361.83  362.05    -1.0
2026-03-27 15:59:00-04:00  362.05  362.62  361.73  361.75    -1.0

[135210 rows x 5 columns]